- name: setting backend
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing  nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: creating user
    ansible.builtin.user:
      name: expense
  
